repos:
  - repo: local
    hooks:
      - id: mkdocs-build
        name: Build MkDocs documentation
        entry: uv run --with mkdocs --with mkdocstrings-python mkdocs build
        language: system
        pass_filenames: false
        args: ["--config-file", "mkdocs/mkdocs.yml", "--site-dir", "site"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.0 # keep in sync with pyproject.toml
    hooks:
      - id: ruff
        name: Run linter
      - id: ruff-format
        name: Run formatter
        args: ["--check"]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        name: Strip outputs from Jupyter notebooks
